channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - pandoc
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_7
  - bwidget=1.9.11=0
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.6.16=hecc5488_0
  - cairo=1.16.0=h18b612c_1001
  - curl=7.65.2=hf8cf82a_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_7
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_7
  - glib=2.58.3=h6f030ca_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gsl=2.5=h294904e_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_7
  - harfbuzz=2.4.0=h37c48d4_1
  - icu=58.2=hf484d3e_1000
  - jpeg=9c=h14c3975_1001
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=10_openblas
  - libcblas=3.8.0=10_openblas
  - libcurl=7.65.2=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=10_openblas
  - libopenblas=0.3.6=h6e990d7_4
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_1
  - lz4-c=1.8.3=he1b5a44_1001
  - make=4.2.1=h14c3975_2004
  - ncurses=6.1=hf484d3e_1002
  - openblas=0.3.6=h6e990d7_4
  - openssl=1.1.1c=h516909a_0
  - pango=1.40.14=he7ab937_1005
  - pcre=8.41=hf484d3e_1003
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h14c3975_1001
  - r-base=3.6.1=h8900bf8_2
  - r-base64enc=0.1_3=r36h96ca727_4
  - r-digest=0.6.18=r36h96ca727_0
  - r-evaluate=0.13=r36h6115d3f_0
  - r-glue=1.3.1=r36h96ca727_0
  - r-highr=0.8=r36h6115d3f_0
  - r-htmltools=0.3.6=r36h29659fb_0
  - r-jsonlite=1.6=r36h96ca727_0
  - r-knitr=1.22=r36h6115d3f_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-markdown=0.9=r36h96ca727_0
  - r-mime=0.6=r36h96ca727_0
  - r-rcpp=1.0.1=r36h29659fb_0
  - r-rmarkdown=1.12=r36h6115d3f_0
  - r-stringi=1.4.3=r36h29659fb_0
  - r-stringr=1.4.0=r36h6115d3f_0
  - r-tinytex=0.12=r36h6115d3f_0
  - r-xfun=0.6=r36h6115d3f_0
  - r-yaml=2.2.0=r36h96ca727_0
  - readline=8.0=hf8c457e_0
  - sed=4.7=h1bed415_1000
  - tk=8.6.9=hed695b0_1002
  - tktable=2.10=h555a92e_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1005
  - zstd=1.4.0=h3b9ef0a_0
  - pandas
  - matplotlib
  - seaborn
  - numpy
